---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: check-merge-conflict
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-xml
          - id: check-ast

    - repo: https://github.com/codespell-project/codespell
      rev: v2.2.6
      hooks:
          - id: codespell
            name: codespell
            description: Checks for common misspellings in text files.
            entry: codespell  *
            language: python
            types: [text]

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3
      hooks:
          - id: yamlfmt
            files: ^.github|./\.yaml

    - repo: https://github.com/psf/black
      rev: 24.4.2
      hooks:
        - id: black
          args: ["--line-length=120", "--preview"]

    - repo: https://github.com/PyCQA/flake8
      rev: 7.1.0
      hooks:
        - id: flake8
          args: ["--config=python_linter.flake8"]

    - repo: https://github.com/PyCQA/doc8
      rev: v1.1.1
      hooks:
        - id: doc8
          args: ['--max-line-length=120', '--ignore=D001']
