---
name: Build and Test (iron)

on:
    push:
        branches: [iron]

    pull_request:
        branches: [iron]

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: ubuntu:jammy

        steps:
            - uses: ros-tooling/setup-ros@v0.7
              with:
                  use-ros2-testing: true
            - uses: ros-tooling/action-ros-ci@v0.3
              with:
                  target-ros2-distro: iron
