---
name: Build and Test (jazzy)

on:
    push:
        branches: [jazzy]

    pull_request:
        branches: [jazzy]

    workflow_dispatch:

jobs:
    build:
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
        runs-on: ubuntu-latest
        container:
            image: ubuntu:noble

        steps:
            - uses: ros-tooling/setup-ros@v0.7
              with:
                  use-ros2-testing: true
            - uses: ros-tooling/action-ros-ci@v0.3
              with:
                  target-ros2-distro: jazzy
