---
name: Build and Test (rolling)

on:
    push:
        branches: [rolling]

    pull_request:
        branches: [rolling]

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: ubuntu:noble

        steps:
            - uses: ros-tooling/setup-ros@v0.7
              with:
                  use-ros2-testing: true
            - uses: ros-tooling/action-ros-ci@v0.3
              with:
                  target-ros2-distro: rolling

    ament_lint_general:
        name: ament_${{ matrix.linter }}
        runs-on: ubuntu-latest
        container:
            image: rostooling/setup-ros-docker:ubuntu-noble-ros-rolling-ros-base-latest
        strategy:
            fail-fast: false
            matrix:
                linter: [xmllint, pep257]
        steps:
            - uses: actions/checkout@v4
            - uses: ros-tooling/action-ros-lint@v0.1
              with:
                  linter: ${{ matrix.linter }}
                  distribution: rolling
                  package-name: human_detector
    ament_flake8:
        name: ament_flake8
        runs-on: ubuntu-latest
        container:
            image: rostooling/setup-ros-docker:ubuntu-noble-ros-rolling-ros-base-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ros-tooling/action-ros-lint@v0.1
              with:
                  linter: flake8
                  distribution: rolling
                  package-name: human_detector
                  arguments: --config python_linter.flake8
