---
name: Lint
on:
    pull_request:
    push:

jobs:
    ament_lint_general:
        name: ament_${{ matrix.linter }}
        runs-on: ubuntu-latest
        container:
            image: rostooling/setup-ros-docker:ubuntu-jammy-ros-humble-ros-base-latest
        strategy:
            fail-fast: false
            matrix:
                linter: [xmllint, pep257]
        steps:
            - uses: actions/checkout@v4
            - uses: ros-tooling/action-ros-lint@v0.1
              with:
                  linter: ${{ matrix.linter }}
                  distribution: humble
                  package-name: human_detector
    ament_flake8:
        name: ament_flake8
        runs-on: ubuntu-latest
        container:
            image: rostooling/setup-ros-docker:ubuntu-jammy-ros-humble-ros-base-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ros-tooling/action-ros-lint@v0.1
              with:
                  linter: flake8
                  distribution: humble
                  package-name: human_detector
                  arguments: --config python_linter.flake8
