name: Lint
on:
  pull_request:
  push:

jobs:
    lint:
        name: ament_${{ matrix.linter }}
        runs-on: ubuntu-latest
        container:
            image: ubuntu:jammy
        strategy:
            fail-fast: false
            matrix:
                linter: [xmllint, flake8, pep257]
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Run linter
              uses: ./.github/actions/lint/
              env:
                  LINTER: ${{ matrix.linter }}